removed openmm deprecation warning
IRL2/nanover-protocol pull request #93
Opened 2024-05-02 12:27 UTC by phuddha

Removed smtk.openmm deprecation warnings.

2024-05-02 12:36 UTC, jbarnoud requested changes
Thank you @phuddha for the PR. I did not realise we used the old imports in so many places, I was convinced we already dealt with this and only had a couple of edge cases. It is a good thing you scanned through.

There are a couple of instances where the `simtk` in the import was part of a try/except construct to handle the deprecation. You fixed one of them but others stayed in their try/except. Could you fix them, please?

2024-05-02 12:36 UTC, jbarnoud commented on python-libraries/nanover-openmm/src/nanover/openmm/converter.py
> +    from openmm import State
Here, and just below, we do not need the try/except construct anymore. The code used to say, "Try importing `State` from `openmm`; if you cannot find it, import it from `simtk.openmm`."

This is the same as what you did in `nanoverreporter.py`.

2024-05-02 12:36 UTC, jbarnoud commented on python-libraries/nanover-openmm/tests_nanover_openmm/test_converter.py
> +    from openmm.app.element import Element
Like above, you do not need the try/except here.

2024-05-16 08:04 UTC, jbarnoud commented
This looks good to go. There are still some occurrences left of `simtk` in various places that we need to get rid of:

```
win_compile.ps1
53:python -c "import simtk"

compile.sh
77:	python -c "import simtk" 2>&1 >/dev/null || {

examples/openmm/OpenMM runner.ipynb
31:    "from simtk import unit\n",

python-libraries/nanover-openmm/tests_nanover_openmm/test_potentials.py
4:from simtk.unit import kilojoule_per_mole, nanometer

python-libraries/nanover-openmm/tests_nanover_openmm/test_imd.py
10:from simtk.unit import nanometer

python-libraries/nanover-openmm/tests_nanover_openmm/simulation_utils.py
14:# Prefixed units in `simtk.unit` are added programmatically and are not
16:from simtk.unit import (

examples/ase/openmm_graphene.ipynb
49:    "import simtk.unit as unit\n",

python-libraries/nanover-openmm/src/nanover/openmm/potentials.py
8:from simtk.unit import Quantity, kilojoule_per_mole, nanometer
23:    >>> from simtk.unit import  kilojoule_per_mole, nanometer

python-libraries/nanover-openmm/src/nanover/openmm/imd.py
60:from simtk import unit

examples/ase/openmm_neuraminidase.ipynb
58:    "import simtk.unit as unit \n",
258:      "Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.\n"

python-libraries/nanover-ase/tests/openmm_ase/simulation_utils.py
16:# Prefixed units in `simtk.unit` are added programmatically and are not
18:from simtk.unit import (

python-libraries/nanover-ase/tests/openmm_ase/test_calculator.py
4:from simtk.unit import (

python-libraries/nanover-ase/src/nanover/ase/openmm/calculator.py
13:from simtk.unit import angstrom, kilojoules_per_mole, kilojoule_per_mole, amu, Quantity
```

Would you mind fixing them too? Otherwise, please open an issue to track the remaining task and I am happy merging this PR as is.

2024-05-20 12:16 UTC, Ragzouken commented
> This looks good to go. There are still some occurrences left of `simtk` in various places that we need to get rid of:
> 
> ```
> win_compile.ps1
> 53:python -c "import simtk"
> 
> compile.sh
> 77:	python -c "import simtk" 2>&1 >/dev/null || {
> 
> examples/openmm/OpenMM runner.ipynb
> 31:    "from simtk import unit\n",
> 
> python-libraries/nanover-openmm/tests_nanover_openmm/test_potentials.py
> 4:from simtk.unit import kilojoule_per_mole, nanometer
> 
> python-libraries/nanover-openmm/tests_nanover_openmm/test_imd.py
> 10:from simtk.unit import nanometer
> 
> python-libraries/nanover-openmm/tests_nanover_openmm/simulation_utils.py
> 14:# Prefixed units in `simtk.unit` are added programmatically and are not
> 16:from simtk.unit import (
> 
> examples/ase/openmm_graphene.ipynb
> 49:    "import simtk.unit as unit\n",
> 
> python-libraries/nanover-openmm/src/nanover/openmm/potentials.py
> 8:from simtk.unit import Quantity, kilojoule_per_mole, nanometer
> 23:    >>> from simtk.unit import  kilojoule_per_mole, nanometer
> 
> python-libraries/nanover-openmm/src/nanover/openmm/imd.py
> 60:from simtk import unit
> 
> examples/ase/openmm_neuraminidase.ipynb
> 58:    "import simtk.unit as unit \n",
> 258:      "Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.\n"
> 
> python-libraries/nanover-ase/tests/openmm_ase/simulation_utils.py
> 16:# Prefixed units in `simtk.unit` are added programmatically and are not
> 18:from simtk.unit import (
> 
> python-libraries/nanover-ase/tests/openmm_ase/test_calculator.py
> 4:from simtk.unit import (
> 
> python-libraries/nanover-ase/src/nanover/ase/openmm/calculator.py
> 13:from simtk.unit import angstrom, kilojoules_per_mole, kilojoule_per_mole, amu, Quantity
> ```
> 
> Would you mind fixing them too? Otherwise, please open an issue to track the remaining task and I am happy merging this PR as is.

Worth clarifying something that wasn't obvious to me: `simtk.unit` is just an alias for `openmm.unit`, which is why it makes sense to address it as part of this issue. I can't see `simtk` it anywhere in our list of dependencies so I have no idea how it's getting installed in the first place..

2024-05-20 14:07 UTC, jbarnoud commented
openmm historically was part of the simtk project. IIRC there is no simtk package, but openmm creates the simtk module. It was confusing people so they decided to get rid of the simtk module and make all accesses go through an openmm module instead.

2024-06-13 10:35 UTC, Ragzouken approved these changes

2024-06-13 10:44 UTC, merged

2024-06-13 10:44 UTC, Ragzouken commented
All looks good.